export const FLOOR_MATERIALS = [
  {
    id: "wood_ash",
    label: "Wood Ash",
    baseColor: "/textures/floors/Wood_Floor_Ash/Poliigon_WoodFloorAsh_4186_BaseColor.jpg",
    normal: "/textures/floors/Wood_Floor_Ash/Poliigon_WoodFloorAsh_4186_Normal.png",
    roughness: "/textures/floors/Wood_Floor_Ash/Poliigon_WoodFloorAsh_4186_Roughness.jpg",
    repeat: [4, 4],
  },
  {
    id: "tiles_ceramic",
    label: "Ceramic Tiles",
    baseColor: "/textures/floors/Tiles_Cermic/Poliigon_TilesCeramicWhite_6956_BaseColor.jpg",
    normal: "/textures/floors/Tiles_Cermic/Poliigon_TilesCeramicWhite_6956_Normal.png",
    roughness: "/textures/floors/Tiles_Cermic/Poliigon_TilesCeramicWhite_6956_Roughness.jpg",
    repeat: [4, 4],
  },
  {
    id: "tiles_slate",
    label: "Slate Tiles",
    baseColor: "/textures/floors/Tiles_Slate/Poliigon_SlateFloorTile_7657_BaseColor.jpg",
    normal: "/textures/floors/Tiles_Slate/Poliigon_SlateFloorTile_7657_Normal.png",
    roughness: "/textures/floors/Tiles_Slate/Poliigon_SlateFloorTile_7657_Roughness.jpg",
    repeat: [4, 4],
  },
  {
    id: "terrazzo",
    label: "Terrazzo",
    baseColor: "/textures/floors/Terrazzo/TerrazzoSlab018_COL_2K_BaseColor.png",
    normal: "/textures/floors/Terrazzo/TerrazzoSlab018_NRM_2K_Normal.png",
    roughness: "/textures/floors/Terrazzo/TerrazzoSlab018_ROUGHNESS_2K_Roughness.png",
    repeat: [4, 4],
  },
];
export const WALL_MATERIALS = [
  {
    id: "brick",
    label: "Brick Wall",
    baseColor: "/textures/walls/Brick_wall/Poliigon_BrickWallReclaimed_8320_BaseColor.jpg",
    normal: "/textures/walls/Brick_wall/Poliigon_BrickWallReclaimed_8320_Normal.png",
    roughness: "/textures/walls/Brick_wall/Poliigon_BrickWallReclaimed_8320_Roughness.jpg",
    repeat: [2, 2],
  },
  {
    id: "concrete",
    label: "Concrete",
    baseColor: "/textures/walls/Concrete/Poliigon_CeramicPotteryGlazed_10861_BaseColor.jpg",
    normal: "/textures/walls/Concrete/Poliigon_CeramicPotteryGlazed_10861_Normal.png",
    roughness: "/textures/walls/Concrete/Poliigon_CeramicPotteryGlazed_10861_Roughness.jpg",
    repeat: [2, 2],
  },
  {
    id: "concrete_worn",
    label: "Worn Concrete",
    baseColor: "/textures/walls/Concrete_worn/Poliigon_ConcreteWorn_8690_BaseColor.jpg",
    normal: "/textures/walls/Concrete_worn/Poliigon_ConcreteWorn_8690_Normal.png",
    roughness: "/textures/walls/Concrete_worn/Poliigon_ConcreteWorn_8690_Roughness.jpg",
    repeat: [2, 2],
  },
];
